// Package tier1a is the runtime executor for the Tier 1A signature SQL cache.
//
// Tier 1A is LLM-free at runtime: we just execute the cached SQL against
// unified_events and emit findings for any hit. The cache was generated by
// internal/rulebuild during the build phase. See CLAUDE.md "★ TLVB 設計の
// 確定事項 → Tier 1A は runtime LLM ゼロ".
//
// Output layout:
//   outputs/cases/<id>/findings/by-rule/<rule_source>/<rule_id>.json
//
// Each output file holds ONE Finding (1 rule = 1 finding regardless of hit count).
// Multiple hits become entries inside Finding.Evidence.
package tier1a

import "time"

// Finding is the per-rule output emitted by the runtime when a cached SQL
// matched at least one event. See docs/DESIGN.md §3.4 for schema rationale.
type Finding struct {
	FindingID    string        `json:"finding_id"`
	CaseID       string        `json:"case_id"`
	RuleID       string        `json:"rule_id"`
	RuleSource   string        `json:"rule_source"`
	RuleMeta     RuleMeta      `json:"rule_meta"`
	Evidence     []EvidenceRef `json:"evidence"`
	MatchCount   int           `json:"match_count"`         // total matches (may exceed len(Evidence) if capped)
	Truncated    bool          `json:"truncated,omitempty"` // true if MatchCount > MaxEvidence

	// Review Gate 1A state.
	Approved     bool   `json:"approved"`
	ApprovedBy   string `json:"approved_by,omitempty"`   // "auto:severity-rule" | examiner name
	RejectReason string `json:"reject_reason,omitempty"`

	// Audit trail.
	GeneratedAt time.Time `json:"generated_at"`
	SQL         string    `json:"sql"` // the executed SQL — useful when triaging false positives
}

// RuleMeta is the subset of rule_meta the runtime forwards to findings.
// Sigma/Hayabusa carry richer info; we project just what the Review UI
// and Reporter need.
type RuleMeta struct {
	Title           string   `json:"title,omitempty"`
	Description     string   `json:"description,omitempty"`
	Level           string   `json:"level,omitempty"` // critical | high | medium | low | informational
	MITRETechniques []string `json:"mitre_techniques,omitempty"`
	MITRETactics    []string `json:"mitre_tactics,omitempty"`
	SourcePath      string   `json:"source_path,omitempty"` // rules/sigma/.../*.yml
}

// EvidenceRef is one matched event row, with the four canonical columns
// (audit_id / ts_utc / artifact_id / event_type) plus whatever extra
// columns the LLM-generated SQL projected.
type EvidenceRef struct {
	AuditID    string         `json:"audit_id"`
	TsUTC      *time.Time     `json:"ts_utc,omitempty"` // pointer because shimcache etc. emit NULL
	ArtifactID string         `json:"artifact_id"`
	EventType  string         `json:"event_type"`
	Extra      map[string]any `json:"extra,omitempty"` // SQL projection columns beyond the canonical 4
}

// AutoApproveByLevel implements the severity-based default for Review Gate 1A.
// critical/high require Examiner review (Approved=false);
// medium/low/informational are auto-approved.
// Override at the Examiner level via the Review UI.
func AutoApproveByLevel(level string) (approved bool, approvedBy string) {
	switch level {
	case "critical", "high":
		return false, ""
	case "medium", "low", "informational", "":
		return true, "auto:severity-rule"
	default:
		return true, "auto:severity-rule"
	}
}
