#!/usr/bin/env python3
"""Generate docs/TEST_FEATURES.csv from the canonical feature inventory.

The CSV is for Excel / Google Sheets / LibreOffice users who want to
tick off test items with a check column. UTF-8 BOM + RFC-4180 quoting
so Excel auto-detects encoding on Windows / Mac alike.

Source of truth: this script. Markdown (`docs/TEST_FEATURES.md`) and CSV
are both generated views of the same feature list — keep this script
in sync when adding new features.
"""

from __future__ import annotations

import csv
import pathlib
import sys


# -------------------------------------------------------------------------
# Feature inventory — single source of truth.
# Tuple: (id, category, feature, related_files, related_issues, automation,
#         expected, prior_status)
# -------------------------------------------------------------------------

FEATURES: list[tuple[str, str, str, str, str, str, str, str]] = [
    # ====================================================================
    # 1. 証拠取り込み
    # ====================================================================
    ("F1-01", "1. 証拠取り込み", "zip / ディレクトリ取り込み",
     "parsers/orchestrator.py::stage_input",
     "",
     "tests/parsers/test_archive.py (12)",
     "extracted/ にファイル展開、actions.jsonl に stage:extracting 記録",
     "pass"),
    ("F1-02", "1. 証拠取り込み", "ネスト解凍 (.zip / .7z / .tar / .tar.gz / .tar.bz2 / .tar.xz / .gz)",
     "parsers/_archive.py",
     "v0.4 REQ-1",
     "tests/parsers/test_archive.py (12)",
     "extracted/__nested__/<sha8>/ に再帰展開、depth=4 / ratio=200x / size=50GiB cap",
     "pass"),
    ("F1-03", "1. 証拠取り込み", "ディスクイメージ取り込み (E01 / raw / dd / img)",
     "parsers/image_extractor.py",
     "#23",
     "tests/parsers/test_image_extractor.py (12)",
     "extract.log JSONL 出力、$MFT/$LogFile 抽出、Extracts セクション表示",
     "pass"),
    ("F1-04", "1. 証拠取り込み", "ディスクイメージ取り込み (VMDK / VHD / VHDX)",
     "parsers/image_extractor.py::_mount_image (qemu-nbd)",
     "#23",
     "",
     "qemu-nbd + sudo + nbd モジュール経由でマウント、CI 不可",
     "skip"),
    ("F1-05", "1. 証拠取り込み", "CDIR 形式取り込み",
     "parsers/orchestrator.py::detect (既存 **/glob)",
     "#23",
     "",
     "input_mode=cdir で dir 処理、EVTX/ Registry/ 等のカテゴリ folder を自動検出",
     "pass"),
    ("F1-06", "1. 証拠取り込み", "Washizukami-Collector 形式",
     "parsers/washizukami_audit_parser.py",
     "v0.3 #12",
     "",
     "collection.log から source_path / sha256 / status を unified_events に展開",
     "partial"),
    ("F1-07", "1. 証拠取り込み", "複数 Evidence 同時受付",
     "cmd/findevil/main.go::runParse / internal/web/handlers.go::handleStartParse",
     "v0.3 #1",
     "",
     "順次処理、1 つ失敗で他継続 (graceful)、Tier 1 で全 evidence をプール",
     "pass"),
    ("F1-08", "1. 証拠取り込み", "SHA-256 fingerprint",
     "cmd/findevil/main.go::evidenceFingerprint",
     "",
     "",
     "file は SHA-256、dir は dir:<sha8> タグ、evidence テーブルに保存",
     "pass"),
    ("F1-09", "1. 証拠取り込み", "ケース export / import (.fcz tarball)",
     "internal/exporter/case_export.go / case_import.go",
     "#16",
     "",
     "SHA-256 整合保証 + round-trip + tamper detection",
     "pass"),

    # ====================================================================
    # 2. アーティファクト解析 (17 種パーサ)
    # ====================================================================
    ("F2-01", "2. パーサ", "EVTX (EvtxECmd 1.5.2.0)",
     "parsers/evtx_parser.py", "", "",
     "exit_code=0、unified_events 行数>0、events に Provider/EventId/Computer",
     "pass"),
    ("F2-02", "2. パーサ", "Amcache (AmcacheParser 1.5.2.0)",
     "parsers/amcache_parser.py", "", "",
     "Amcache.hve から application / driver / file テーブル統合",
     "partial-smoke"),
    ("F2-03", "2. パーサ", "Prefetch (altpf primary, Plaso fallback)",
     "parsers/prefetch_parser.py (altpf @ /opt/altpf/altpf)",
     "#15→#17→#27",
     "tests/parsers/test_altpf_csv_convert.py (14) + test_dynamic_dt.py (8)",
     "altpf -d で 215 .pf を 0.187s parse, LastRun+PreviousRun0..6 を独立 unified_event 行で展開. 失敗時 Plaso fallback.",
     "pass"),
    ("F2-04", "2. パーサ", "Registry (RECmd Kroll Batch)",
     "parsers/registry_parser.py", "", "",
     "SYSTEM/SOFTWARE/SAM/SECURITY/DEFAULT/NTUSER 全 hive 統合",
     "partial-smoke"),
    ("F2-05", "2. パーサ", "Scheduled Tasks (Plaso winjob/winreg)",
     "parsers/scheduled_tasks_parser.py", "", "",
     "Tasks XML から trigger / action / runas 抽出",
     "partial-smoke"),
    ("F2-06", "2. パーサ", "Shimcache (AppCompatCacheParser 1.5.1.0)",
     "parsers/shimcache_parser.py", "", "",
     "SYSTEM hive 内 AppCompatCache キーから直接 parse",
     "partial-smoke"),
    ("F2-07", "2. パーサ", "MFT ($MFT) — MFTECmd 1.3.0.0",
     "parsers/mft_parser.py", "",
     "verify.sh [3/8]",
     "$SI 0x10 + $FN 0x30 timestamps、deleted 含む",
     "pass"),
    ("F2-08", "2. パーサ", "Shellbags (SBECmd 2.1.0.0)",
     "parsers/shellbags_parser.py", "", "",
     "NTUSER.DAT / UsrClass.DAT から navigation history 復元",
     "partial-smoke"),
    ("F2-09", "2. パーサ", "Jumplists (JLECmd 1.5.1.0)",
     "parsers/jumplists_parser.py", "", "",
     "AutomaticDestinations / CustomDestinations から MRU + LNK 抽出",
     "partial-smoke"),
    ("F2-10", "2. パーサ", "LNK Files (LECmd 1.5.1.0)",
     "parsers/lnk_parser.py", "", "",
     ".lnk ファイルから target path / volume / network share 抽出",
     "partial-smoke"),
    ("F2-11", "2. パーサ", "Recycle Bin (RBCmd 1.6.1.0)",
     "parsers/recyclebin_parser.py", "", "",
     "$I / $R ファイルから削除されたファイルメタデータ復元",
     "partial-smoke"),
    ("F2-12", "2. パーサ", "Win10 Timeline (WxTCmd 1.1.0.0)",
     "parsers/win10timeline_parser.py", "", "",
     "ActivitiesCache.db から activity timeline 抽出",
     "partial-smoke"),
    ("F2-13", "2. パーサ", "Browser History (Chrome / Edge / Firefox)",
     "parsers/browser_history_parser.py", "v0.3 #5", "",
     "stdlib sqlite3 で immutable=1 read-only、WebKit/PRTime → ISO 変換",
     "partial-smoke"),
    ("F2-14", "2. パーサ", "USN journal ($J) — MFTECmd",
     "parsers/usn_journal_parser.py", "#24",
     "tests/parsers/test_p2_dryrun.py + test_orchestrator_route.py",
     "MFTECmd -f $J [-m $MFT]、sibling $MFT 自動検出で FRN→path",
     "pass"),
    ("F2-15", "2. パーサ", "Hayabusa (Sigma EVTX, optional)",
     "parsers/hayabusa_parser.py", "#24",
     "tests/parsers/test_p2_dryrun.py",
     "バイナリ未配置で install hint + skip、配置時は EVTX 検出時に自動 schedule",
     "pass (graceful skip)"),
    ("F2-16", "2. パーサ", "SRUM (Plaso primary, SrumECmd Windows fallback)",
     "parsers/srum_parser.py (psteal --parsers esedb/srum)",
     "#24 → Wave 13",
     "tests/parsers/test_srum_plaso_primary.py (11) + test_p2_dryrun.py (6)",
     "TANAKA-PC SRUDB.dat (1.9 MB) を Plaso esedb/srum で 1404 events / 3.2s, SrumECmd は Linux 不可で fallback",
     "pass"),
    ("F2-17", "2. パーサ", "Washizukami Audit Sample",
     "parsers/washizukami_audit_parser.py", "v0.3 #12", "",
     "FOR508 Workshop 合成サンプル → SHA-256 + source_path 復元",
     "partial"),

    # ====================================================================
    # 3. 自動分析 (Tactic Agent)
    # ====================================================================
    ("F3-01", "3. 自動分析", "10 標準 Tactic Agent (TA0001〜TA0040)",
     "internal/agents/tactic_queries.go + skills/<slug>.md",
     "",
     "",
     "各 tactic で findings/<slug>.json 生成、TacticReport schema 準拠",
     "pass (Persistence で代表検証)"),
    ("F3-02", "3. 自動分析", "Anomaly Hunter (Tier 1.5)",
     "internal/agents/anomaly_hunter.go + skills/anomaly_hunter.md",
     "",
     "",
     "category-less な異常検出、出力 finding 形式は他 Tactic と同じ",
     "deferred (LLM コスト)"),
    ("F3-03", "3. 自動分析", "SQL prefilter (Tactic ごと)",
     "internal/agents/tactic_queries.go::TacticRegistry",
     "",
     "",
     "findings/<slug>.json::audit.events_input が prefilter 後の件数",
     "deferred (LLM コスト)"),
    ("F3-04", "3. 自動分析", "engine=claude-code (CLI)",
     "internal/agents/claude_code.go",
     "",
     "",
     "actions.jsonl に engine=claude-code 記録、claude CLI セッション流用",
     "pass (F3-01 で同時検証)"),
    ("F3-05", "3. 自動分析", "engine=anthropic-api (Prompt Cache)",
     "internal/agents/anthropic.go",
     "",
     "",
     "ANTHROPIC_API_KEY 経由、cache_creation_tokens > 0 (初回)、cache_read > 0 (2 回目)",
     "deferred (LLM コスト)"),
    ("F3-06", "3. 自動分析", "graceful degradation (1 fail → 他継続)",
     "cmd/findevil/main.go::runFullPipeline",
     "",
     "",
     "--tactic-timeout 1 で 1 つ強制失敗、他 9 完走、ケース succeeded",
     "deferred (LLM コスト)"),
    ("F3-07", "3. 自動分析", "cap (max_iter / max_tokens / timeout)",
     "internal/agents/runner.go::Config",
     "",
     "",
     "--iters 0 で即停止、cap_hit:true 記録、ケースは continue",
     "deferred (LLM コスト)"),

    # ====================================================================
    # 4. 統合 (Synthesizer)
    # ====================================================================
    ("F4-01", "4. 統合", "Aggregator (union-find クラスタリング)",
     "internal/synthesizer/aggregator.go",
     "",
     "",
     "finding_clusters[].finding_ids に同 audit_id の重複統合",
     "pass"),
    ("F4-02", "4. 統合", "ConsistencyChecker R1 (audit_id 未解決)",
     "internal/synthesizer/consistency.go",
     "",
     "",
     "架空 audit_id 検出 → inconsistencies[].rule=R1",
     "partial (smoke)"),
    ("F4-03", "4. 統合", "ConsistencyChecker R2 (時間矛盾)",
     "internal/synthesizer/consistency.go", "", "",
     "Persistence → Execution の時間逆転で R2 警告",
     "partial (smoke)"),
    ("F4-04", "4. 統合", "ConsistencyChecker R3 (single-host lateral)",
     "internal/synthesizer/consistency.go", "", "",
     "Lateral Movement finding が 1 host のみ → R3 + resolution suggest",
     "partial (F1-01 で発火)"),
    ("F4-05", "4. 統合", "ConsistencyChecker R4 (kill chain 飛び)",
     "internal/synthesizer/consistency.go", "", "",
     "Initial Access + Impact のみで R4 警告",
     "partial (smoke)"),
    ("F4-06", "4. 統合", "TimelineBuilder (Plaso 準拠)",
     "internal/synthesizer/timeline.go", "", "",
     "timeline[].ts_utc ソート安定性、artifact_id/computer/confidence 完備",
     "pass"),
    ("F4-07", "4. 統合", "inferAttackSteps (Kill Chain)",
     "internal/synthesizer/timeline.go::inferAttackSteps", "", "",
     "intrusion_path[].tactic が TA0001 → TA0040 順、同時刻タイブレーク安定",
     "pass"),
    ("F4-08", "4. 統合", "Corrector (max_rounds=1)",
     "internal/synthesizer/corrector.go", "", "",
     "actionable warning 抽出 → 関連 Tactic 再走 → Resolved/Unresolved 分離",
     "deferred (LLM コスト)"),
    ("F4-09", "4. 統合", "TimelineReviewer (12 観点)",
     "internal/synthesizer/timeline_review.go + skills/timeline_review.md",
     "v0.5",
     "",
     "kill_chain_order / time_gap / off_hours / burst / velocity / lateral_movement_speed / "
     "execution_corroboration / persistence_dormancy / defense_evasion_bookend / "
     "anti_forensic / multi_host_correlation / account_lifecycle の 12 観点 finding",
     "deferred (LLM コスト)"),

    # ====================================================================
    # 5. レポート出力
    # ====================================================================
    ("F5-01", "5. レポート", "HTML 11 セクション",
     "internal/reporter/html_report.go",
     "",
     "",
     "§1 Executive / §2 Scope / §3 Intrusion Path / §4 Timeline / §5 Findings / "
     "§6 Inconsistencies / §7 Recommendations / §8 IOCs / §9 MITRE / §10 Audit / "
     "§10b Failed Artifacts / §11 Appendix",
     "pass"),
    ("F5-02", "5. レポート", "CSV 4 ファイル + UTF-8 BOM",
     "internal/reporter/csv_report.go",
     "#26",
     "",
     "findings/timeline/iocs.csv に BOM、failed_artifacts.csv は失敗時のみ",
     "pass"),
    ("F5-03", "5. レポート", "JSON 出力 (case-synthesis/v1)",
     "internal/reporter/json_report.go",
     "",
     "",
     "schema findevil/case-synthesis/v1、全フィールド網羅",
     "pass"),
    ("F5-04", "5. レポート", "多言語 ja / en",
     "internal/reporter/renderer.go::dictJA/dictEN",
     "#22",
     "",
     "--language ja で英単語残ゼロ (固有名詞 allowlist 除く)、en で日本語残ゼロ",
     "pass (labels) / partial (LLM 本文)"),
    ("F5-05", "5. レポート", "--only-approved フィルタ",
     "internal/reporter/renderer.go::filterToApproved",
     "",
     "",
     "Approved finding のみで §5 を render、Rejected/Pending を除外",
     "manual"),
    ("F5-06", "5. レポート", "MITRE Mapping table",
     "internal/synthesizer/synthesizer.go::buildMITREMapping",
     "",
     "",
     "§9 に tactic × technique × evidence_count × max confidence",
     "pass"),
    ("F5-07", "5. レポート", "Failed Artifacts セクション (§10b)",
     "internal/synthesizer/synthesizer.go::collectFailedArtifacts + html_report.go",
     "#26",
     "",
     "失敗 parser がある case で §10b に表示、failed_artifacts.csv 生成",
     "pass"),

    # ====================================================================
    # 6. レビューゲート
    # ====================================================================
    ("F6-01", "6. Review Gate", "Gate 0 (Parse Results) 個別 approve/reject",
     "internal/web/parse_review.go",
     "v0.3 #2",
     "",
     "POST /api/cases/<id>/parse-review/<artifact>/approve → state=approved",
     "pass"),
    ("F6-02", "6. Review Gate", "Gate 0 — skip-all=true で auto_skip",
     "internal/web/parse_review.go",
     "#11/#12",
     "",
     "POST /parse-review/skip-all {auto_skip:true} → pending 全部 skipped",
     "pass"),
    ("F6-03", "6. Review Gate", "Gate 0 — Extracts セクション (image 抽出)",
     "internal/web/extract_review.go",
     "#23",
     "",
     "image 入力 case で GET /api/cases/<id>/extracts → records 配列、approve/reject 可",
     "pass (F1-03 で同時検証)"),
    ("F6-04", "6. Review Gate", "Gate 1 (Findings) bulk approve/reject/reset",
     "internal/web/handlers.go::handleBulkFindingsAction",
     "#5/#7/#10",
     "",
     "POST /findings/bulk {action: approve, finding_ids: [...]} で一括",
     "pass"),
    ("F6-05", "6. Review Gate", "Gate 1 — Reject reason 任意化",
     "internal/web/handlers.go + ui/static/app.js + internal/review/gate.go",
     "#21",
     "tests/web/test_handlers_validate.py",
     "空 reason で reject → 200",
     "pass (auto)"),
    ("F6-06", "6. Review Gate", "Gate 2 (Timeline)",
     "(設計のみ、未実装)",
     "",
     "",
     "設計のみ。実装後に再評価",
     "deferred"),

    # ====================================================================
    # 7. CLI (10 subcommand)
    # ====================================================================
    ("F7-01", "7. CLI", "findevil version",
     "cmd/findevil/main.go::runVersion",
     "",
     "",
     "exit 0、`findevil 0.X.X-dev` 出力",
     "pass"),
    ("F7-02", "7. CLI", "findevil case init",
     "cmd/findevil/main.go",
     "",
     "",
     "DB に case 行作成、SHA-256 更新",
     "pass"),
    ("F7-03", "7. CLI", "findevil case export / import (.fcz)",
     "internal/exporter/",
     "#16",
     "",
     "F1-09 と同等 (.fcz round-trip + tamper detection)",
     "pass"),
    ("F7-04", "7. CLI", "findevil parse [--input/--inputs/--input-mode/--image-format]",
     "cmd/findevil/main.go::runParse",
     "",
     "",
     "F1-01 / F1-03 / F1-07 と同等",
     "pass"),
    ("F7-05", "7. CLI", "findevil analyze [--tactic/--engine]",
     "cmd/findevil/main.go::runAnalyze",
     "",
     "",
     "F3-01〜F3-07 (LLM 必要)",
     "pass (F3-01 で代表検証)"),
    ("F7-06", "7. CLI", "findevil synthesize [--correct/--review-timeline]",
     "cmd/findevil/main.go::runSynthesize",
     "",
     "",
     "F4-01〜F4-09",
     "pass"),
    ("F7-07", "7. CLI", "findevil report [--language/--only-approved/--json]",
     "cmd/findevil/main.go::runReport",
     "",
     "",
     "F5-01〜F5-07",
     "pass"),
    ("F7-08", "7. CLI", "findevil review (対話 Gate 1)",
     "internal/review/gate.go",
     "",
     "",
     "a/r/s/S/q 全動作、Reject reason 空 OK (#21)",
     "manual"),
    ("F7-09", "7. CLI", "findevil run (一括パイプライン)",
     "cmd/findevil/main.go::runFullPipeline",
     "",
     "",
     "parse → analyze → synth → report を順に実行",
     "manual (LLM 必要)"),
    ("F7-10", "7. CLI", "findevil serve / mcp-serve",
     "internal/web/server.go / internal/mcp/server.go",
     "",
     "",
     "port listen → /api/cases で 200、MCP は stdio で handshake",
     "pass"),

    # ====================================================================
    # 8. Web UI / REST API
    # ====================================================================
    ("F8-01", "8. Web UI", "21 REST endpoint (case/parse/analyze/synth/report/events 等)",
     "internal/web/server.go",
     "",
     "",
     "全 endpoint が 200 or 4xx で応答",
     "pass (11 endpoint smoke)"),
    ("F8-02", "8. Web UI", "7 タブ (Events/Findings/Timeline/IOC/MITRE/Report/Audit)",
     "ui/static/app.js",
     "",
     "",
     "ブラウザで /cases/<id> 開いて各タブ表示",
     "manual"),
    ("F8-03", "8. Web UI", "Extracts セクション (Events タブ内)",
     "ui/static/app.js::renderExtractsSection",
     "#23",
     "",
     "image 入力 case で Events タブに「Extracts — Review Gate 0 (image)」表示",
     "manual (F1-03 WebUI test に同梱)"),
    ("F8-04", "8. Web UI", "Job 進捗バー + キャンセル",
     "internal/web/jobs.go::JobsManager",
     "#8",
     "",
     "parse 中に POST /<id>/parse/cancel → state=canceled",
     "manual"),
    ("F8-05", "8. Web UI", "Floating Assistant chat",
     "internal/web/chat.go",
     "",
     "",
     "POST /api/chat {message:\"...\"} で findings 引用付き応答",
     "manual (LLM 必要)"),
    ("F8-06", "8. Web UI", "Case 作成 — Timezone / Language プルダウン",
     "ui/static/app.js::supportedTimezones / SUPPORTED_LANGUAGES",
     "#19/#25",
     "",
     "Timezone セレクタに 100+ オプション、Language は ja / en の 2 択",
     "manual"),
    ("F8-07", "8. Web UI", "Evidence row drill-down (時刻+payload 全文)",
     "ui/static/app.js::loadEvidencePayloads",
     "#20",
     "tests/web/test_handlers_validate.py",
     "finding expand → evidence rows expand → 各 row に time/event_type/payload",
     "pass (audit_id filter auto) / manual (UI 目視)"),
    ("F8-08", "8. Web UI", "Findings filter (all/pending/reviewed)",
     "ui/static/app.js",
     "#4",
     "",
     "Findings タブ右上トグル、.filtered-out で hide",
     "manual"),
    ("F8-09", "8. Web UI", "入力 400 系 (input_mode/image_format/action)",
     "internal/web/handlers.go",
     "#23/#21",
     "tests/web/test_handlers_validate.py (8)",
     "不正値 POST で 400 + error JSON",
     "pass (auto)"),

    # ====================================================================
    # 9. MCP Server
    # ====================================================================
    ("F9-01", "9. MCP", "10 read-only tool",
     "internal/mcp/server.go",
     "",
     "",
     "list_artifacts / get_unified_events / list_findings / get_finding / get_timeline / "
     "get_iocs / get_mitre / list_evidence / get_case_status / get_parse_result",
     "pass (smoke; MCP client 経由検証は手動)"),
    ("F9-02", "9. MCP", "execute_shell 非公開 (architectural guardrail)",
     "internal/mcp/server.go",
     "",
     "",
     "grep -n 'execute_shell' internal/mcp/ → 0 件",
     "pass"),

    # ====================================================================
    # 10. 設定 / 監査 / 環境
    # ====================================================================
    ("F10-01", "10. 設定/監査", "actions.jsonl 監査ログ",
     "parsers/orchestrator.py::append_actions",
     "",
     "",
     "全 stage が JSONL 1 行ずつ、case/parse/synth ステップ毎",
     "pass"),
    ("F10-02", "10. 設定/監査", "PROGRESS|<json> 進捗イベント",
     "parsers/orchestrator.py::_emit",
     "",
     "",
     "findevil parse --progress で stderr に PROGRESS|{...} 行",
     "pass"),
    ("F10-03", "10. 設定/監査", "TZ 一貫性 (UI → orchestrator → parser command)",
     "ui/static/app.js + internal/web/handlers.go + parsers/prefetch_parser.py",
     "#19",
     "tests/parsers/test_dynamic_dt.py",
     "Asia/Tokyo を選んで parse → psort.py -z Asia/Tokyo がコマンドに",
     "pass (helper auto) / manual (E2E)"),
    ("F10-04", "10. 設定/監査", ".env.local 読み込み",
     "internal/common/dotenv.go::LoadDotEnv",
     "",
     "",
     "findevil serve --env-file .env.local で API キー読み込み",
     "manual"),
    ("F10-05", "10. 設定/監査", "/api/health/llm",
     "internal/web/handlers.go::handleHealthLLM",
     "",
     "",
     "curl /api/health/llm で claude CLI / API キーの可用性を返す",
     "pass"),
    ("F10-06", "10. 設定/監査", "rag/build_rag.py (enterprise-attack 限定)",
     "rag/build_rag.py",
     "v0.3 #11",
     "",
     "python3 rag/build_rag.py で MITRE STIX → md 生成、MANIFEST.json",
     "manual"),
    ("F10-07", "10. 設定/監査", "setup.sh --auto-install-deps",
     "scripts/setup.sh",
     "",
     "",
     "python3-venv 等を sudo apt 越しに自動導入",
     "pass (本ランで実行済)"),
    ("F10-08", "10. 設定/監査", "Python venv 自動判定 (#18)",
     "scripts/setup.sh",
     "#18",
     "",
     "python3 -c 'sys.version_info' から MAJOR.MINOR 取り、python${PY_VER}-venv を試行",
     "pass"),
]


# -------------------------------------------------------------------------
# CSV writer
# -------------------------------------------------------------------------

def main(out_path: str) -> int:
    p = pathlib.Path(out_path)
    p.parent.mkdir(parents=True, exist_ok=True)

    # UTF-8 BOM so Excel (Windows / Mac) auto-detects encoding.
    with p.open("w", encoding="utf-8-sig", newline="") as fh:
        w = csv.writer(fh, quoting=csv.QUOTE_MINIMAL, lineterminator="\r\n")
        # Header — チェックを付けやすい順序: ID → 内容 → 状態カラム
        w.writerow([
            "ID",
            "カテゴリ",
            "機能名",
            "関連ファイル / モジュール",
            "関連 Issue",
            "自動化",
            "期待結果",
            "前回状態 (Wave 9 / 10)",
            "今回チェック",
            "実行日",
            "担当",
            "メモ",
        ])
        for row in FEATURES:
            # Pad to 12 columns
            w.writerow([*row, "", "", "", ""])

    print(f"wrote {p} ({len(FEATURES)} features)")
    return 0


if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else "docs/TEST_FEATURES.csv"
    sys.exit(main(out))
